[package]
name = "graph"
version = "0.1.0"
authors = ["Pierre-Antoine Champin <pierre-antoine@champin.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
